"""initial schema

Revision ID: 0001_initial_schema
Revises: 
Create Date: 2026-06-20 02:45:10.048265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_initial_schema'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fact_long',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=16), nullable=False),
    sa.Column('month_number', sa.Integer(), nullable=True),
    sa.Column('period_type', sa.String(length=16), nullable=False),
    sa.Column('reference_date', sa.Date(), nullable=True),
    sa.Column('sex', sa.String(length=16), nullable=False),
    sa.Column('age_group', sa.String(length=32), nullable=False),
    sa.Column('indicator_name', sa.String(length=80), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('source_table', sa.String(length=64), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='clean'
    )
    op.create_index('ix_fact_long_indicator', 'fact_long', ['indicator_name', 'sex', 'age_group'], unique=False, schema='clean')
    op.create_index('ix_fact_long_lookup', 'fact_long', ['source_table', 'year', 'month_number'], unique=False, schema='clean')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_fact_long_lookup', table_name='fact_long', schema='clean')
    op.drop_index('ix_fact_long_indicator', table_name='fact_long', schema='clean')
    op.drop_table('fact_long', schema='clean')
    # ### end Alembic commands ###
